TK1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('relawan/', include('app4.urls')),
    path('listrelawan/', include('app5.urls')),
    path('donasibarang/', include('app3.urls')),
    path('donasiuang/', include('app2.urls')),
    path('otentikasi/', include('otentikasi.urls')),
]

app1/urls.py
from django.urls import path

from . import views

app_name = 'app1'

urlpatterns = [
    path('', views.home, name='home'),
    path('data/', views.data, name='data'),
]

app4/urls.py
from django.urls import path

from . import views

app_name = 'app4'

urlpatterns = [
    path('', views.relawan, name='relawan'),
    path('success/', views.success, name='success'),
    path('confirm/', views.confirm, name='confirm')
]

app4/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

class Relawan(models.Model):
    pilihan_identitas = (
        ('KTP','KTP'),
        ('SIM','SIM'),        
    )
    pilihan_jk = (
        ('Laki-Laki','Laki-Laki'),
        ('Perempuan','Perempuan'),
    )
    pilihan_agama = (
        ('Islam','Islam'),
        ('Kristen Protestan','Kristen Protestan'),
        ('Katolik','Katolik'),
        ('Hindu','Hindu'),
        ('Buddha','Buddha'),
        ('Konghucu','Konghucu'),
        ('Memilih untuk tidak mengisi','Memilih untuk tidak mengisi')
    )
    pilihan_status = (
        ('Belum Kawin','Belum Kawin'),
        ('Sudah Kawin','Sudah Kawin'),
    )
    pilihan_cluster = (
        ('Relawan Medis','Relawan Medis'),
        ('Relawan Jurnalis','Relawan Jurnalis'),
        ('Relawan Media Sosial','Relawan Media Sosial'),
        ('Relawan Creative','Relawan Creative'),
        ('Relawan Fundraising','Relawan Fundraising'),
        ('Relawan Bencana','Relawan Bencana'),
        ('Relawan Pendidikan','Relawan Pendidikan'),
        ('Relawan Programmer','Relawan Programmer'),
    )
    nama = models.CharField(max_length=50,default='')
    nama_panggilan = models.CharField(max_length=50,default='')
    no_hp = models.CharField(max_length=200, default='')
    email = models.CharField(max_length=200,default='')
    identitas = models.CharField(max_length=200, choices=pilihan_identitas)
    no_identitas = models.CharField(max_length=20, default='')
    alamat = models.CharField(max_length=500, default='')
    jenis_kelamin = models.CharField(max_length=100, choices=pilihan_jk)
    kota_kelahiran = models.CharField(max_length=200,default='')
    tanggal_lahir = models.DateField()
    agama = models.CharField(max_length=200, choices=pilihan_agama)
    status = models.CharField(max_length=200, choices=pilihan_status)
    pekerjaan = models.CharField(max_length=200, default='')
    peminatan = models.CharField(max_length=200, choices=pilihan_cluster)
    saya_menyetujui_syarat_dan_ketentuan_yang_berlaku = models.BooleanField(default=False)

app4/forms.py
from django import forms

class relawanForm(forms.Form):
    pilihan_identitas = (
        ('KTP','KTP'),
        ('SIM','SIM'),        
    )
    pilihan_jk = (
        ('Laki-Laki','Laki-Laki'),
        ('Perempuan','Perempuan'),
    )
    pilihan_agama = (
        ('Islam','Islam'),
        ('Kristen Protestan','Kristen Protestan'),
        ('Katolik','Katolik'),
        ('Hindu','Hindu'),
        ('Buddha','Buddha'),
        ('Konghucu','Konghucu'),
        ('Memilih untuk tidak mengisi','Memilih untuk tidak mengisi')
    )
    pilihan_status = (
        ('Belum Kawin','Belum Kawin'),
        ('Sudah Kawin','Sudah Kawin'),
    )
    pilihan_cluster = (
        ('Relawan Medis','Relawan Medis'),
        ('Relawan Jurnalis','Relawan Jurnalis'),
        ('Relawan Media Sosial','Relawan Media Sosial'),
        ('Relawan Creative','Relawan Creative'),
        ('Relawan Fundraising','Relawan Fundraising'),
        ('Relawan Bencana','Relawan Bencana'),
        ('Relawan Pendidikan','Relawan Pendidikan'),
        ('Relawan Programmer','Relawan Programmer'),
    )
    nama = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Isi dengan nama lengkap anda',
        'type' : 'text',
        'required': True,
    }))

    nama_panggilan = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Isi dengan nama panggilan anda',
        'type' : 'text',
        'required': True,
    }))

    no_hp = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Cth: 081234567890',
        'required': True,
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Cth: nama@gmail.com',
        'type' : 'text',
        'required': True,
    }))

    identitas = forms.ChoiceField(choices=pilihan_identitas)
    no_identitas = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Cth: 1234567890XXXX',
        'type' : 'text',
        'required': True,
    }))

    alamat = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Jl. Nama jalan, Nomor rumah, RT/RW, Kelurahan, Kecamatan, Kode Pos, Kota/Kabupaten, Provinsi',
        'type' : 'text',
        'required': True,
    }))
    
    jenis_kelamin = forms.ChoiceField(choices=pilihan_jk)

    kota_kelahiran = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Cth: Depok',
        'type' : 'text',
        'required': True,
    }))

    tanggal_lahir = forms.DateField(widget=forms.DateInput(attrs={
        'class': 'form-control',
        'placeholder' : 'dd/mm/yyyy',
        'type' : 'date',
        'required': True,
    }))

    agama = forms.ChoiceField(choices=pilihan_agama)
    status = forms.ChoiceField(choices=pilihan_status)
    pekerjaan = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Cth: Pegawai Negeri',
        'type' : 'text',
        'required': True,
    }))

    peminatan = forms.ChoiceField(choices=pilihan_cluster)
    saya_menyetujui_syarat_dan_ketentuan_yang_berlaku = forms.BooleanField(required=True)

app4/views.py
from django.shortcuts import render,redirect
from .forms import relawanForm
from .models import Relawan
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

formrelawan = ''
form = ''
def relawan(request):
    if request.method == "POST":
        global form
        form = relawanForm(request.POST)
        if form.is_valid():            
            global formrelawan
            formrelawan = Relawan()
            formrelawan.nama = form.cleaned_data['nama']
            formrelawan.nama_panggilan = form.cleaned_data['nama_panggilan']
            formrelawan.no_hp = form.cleaned_data['no_hp']
            formrelawan.email = form.cleaned_data['email']
            formrelawan.identitas = form.cleaned_data['identitas']
            formrelawan.no_identitas = form.cleaned_data['no_identitas']
            formrelawan.alamat = form.cleaned_data['alamat']
            formrelawan.jenis_kelamin = form.cleaned_data['jenis_kelamin']
            formrelawan.kota_kelahiran = form.cleaned_data['kota_kelahiran']
            formrelawan.tanggal_lahir = form.cleaned_data['tanggal_lahir']
            formrelawan.agama = form.cleaned_data['agama']
            formrelawan.status = form.cleaned_data['status']
            formrelawan.pekerjaan = form.cleaned_data['pekerjaan']
            formrelawan.peminatan = form.cleaned_data['peminatan']  
            
            context = {
                "nama" : form.cleaned_data['nama'],
                "nama_panggilan" : form.cleaned_data['nama_panggilan'],
                "no_hp" : form.cleaned_data['no_hp'],
                "email" : form.cleaned_data['email'],
                "identitas" : form.cleaned_data['identitas'],
                "no_identitas" : form.cleaned_data['no_identitas'],
                "alamat" : form.cleaned_data['alamat'],
                "jenis_kelamin" : form.cleaned_data['jenis_kelamin'],
                "kota_kelahiran" : form.cleaned_data['kota_kelahiran'],
                "tanggal_lahir" : form.cleaned_data['tanggal_lahir'],
                "agama" : form.cleaned_data['agama'],
                "status" : form.cleaned_data['status'],
                "pekerjaan" : form.cleaned_data['pekerjaan'],
                "peminatan" : form.cleaned_data['peminatan']
            }
            
        return JsonResponse(context, safe=False)
    else:
        #relawanall = Relawan.objects.all()
        form = relawanForm()
    
    context = {'form' : form}
    return render(request,'app4.html',context)

def success(request):
    return render(request, 'success.html')

def confirm(request):
    global form
    #form.save()
    global formrelawan
    formrelawan.save()
    send_mail('Selamat Datang Relawan Baru!',
            'Halo! Terimakasih telah melakukan registrasi menjadi relawan kami.\nKami akan segera menghubungi anda bila ada pekerjaan.\nSalam Kebaikan :)\n-Kelompok 8-',
            'ppwkelompok8@gmail.com',
            [formrelawan.email],
            fail_silently=False)  
    return HttpResponseRedirect('/relawan/success')

app4/templates/app4.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}
<html>
  {% block content %} 
    <head>
      <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <title>
            Form Pendaftaran Relawan
        </title>
        <style>
          .popup{
          background:rgba(0,0,0,.4);
          display:none;
          height:100%;
          position:fixed;
          text-align:center;
          top:0;
          width:100%;
          z-index:10000;
        }
        .popup .helper{
          display:inline-block;
          height:100%;
          vertical-align:middle;
        }
        .popup > div {
          background-color: #fff;
          box-shadow: 10px 10px 60px #555;
          display: inline-block;
          height: auto;
          max-width: 551px;
          min-height: 100px;
          vertical-align: middle;
          width: 60%;
          position: relative;
          border-radius: 14px;
          border: 3px solid orange;
          padding: 15px 5%;
        }

        </style>
    </head>
    
    <body style="background-color:orange; font-family: Rubik;">
      {% include 'base.html' %}
      {% if user.is_authenticated %}
		  <div class="container">
        <div class="card" style="margin-top: 50px; margin-bottom: 50px; background-color: rgba(245, 245, 245, 0.9);">
          <div class="container">
        <h2 style="text-align: center; margin-top: 50px; margin-bottom: 10px;">Pendaftaran Relawan</h1>
        <h6 style="text-align: center; margin-bottom: 20px;">Silahkan isi dengan biodata anda</h6>
            <div class="row">
                <div class="col-md-12" style="text-align: left;">
                  
                    <form action="{% url 'app4:relawan' %}" method="POST" id="form_relawan">
                        {% csrf_token %}
                        {{ form.nama|as_crispy_field }}
                        {{ form.nama_panggilan|as_crispy_field }}
                        <div class='form-row'>
                          <div class='form-group col-md-6'>
                            {{ form.no_hp|as_crispy_field }}
                          </div>
                          <div class='form-group col-md-6'>
                            {{ form.email|as_crispy_field }}
                          </div>
                        </div>
                        <div class='form-row'>
                          <div class='form-group col-md-6'>
                            {{ form.identitas|as_crispy_field }}
                          </div>
                          <div class='form-group col-md-6'>
                            {{ form.no_identitas|as_crispy_field }}
                          </div>
                        </div>
                        {{ form.alamat|as_crispy_field }}
                        <div class='form-row'>
                          <div class='form-group col-md-4'>
                            {{ form.jenis_kelamin|as_crispy_field }}
                          </div>
                          <div class='form-group col-md-4'>
                            {{ form.kota_kelahiran|as_crispy_field }}
                          </div>
                          <div class='form-group col-md-4'>
                            {{ form.tanggal_lahir|as_crispy_field }}
                          </div>
                        </div>
                        <div class='form-row'>
                          <div class='form-group col-md-4'>
                            {{ form.agama|as_crispy_field }}
                          </div>
                          <div class='form-group col-md-4'>
                            {{ form.status|as_crispy_field }}
                          </div>
                          <div class='form-group col-md-4'>
                            {{ form.pekerjaan|as_crispy_field }}
                          </div>
                        </div>
                        {{ form.peminatan|as_crispy_field }}
                        {{ form.saya_menyetujui_syarat_dan_ketentuan_yang_berlaku|as_crispy_field }}
                        <div class="centre-items" style="margin-top: 50px; text-align: center;">
                            <input type="submit" class="btn btn-primary" name="btn-form" value="Submit Form" style="margin-bottom: 50px;"></input>
                        </div>
                    </form>
                  
                </div>
        </div>
      </div>
      </div>
      {% else %}
      <div class="container">
        <div class="card" style="margin-top: 50px; margin-bottom: 50px;background-color: rgba(245, 245, 245, 0.9);">
          <div class="container">
            <div class="row">
              <h1 style="margin-top: 50px; margin-bottom: 50px; margin-left: auto; margin-right: auto;">Silahkan Login Terlebih Dahulu</h1>  
            </div>
            <div class="row">
              <div class="centre-items" style="margin-top: 50px; text-align: center; margin-left: auto;margin-right: auto;margin-bottom: 50px;">
                  <a href="/otentikasi/login/"><button class="btn btn-primary">Login Disini</button></a>    
                      </div>               
              </div>
      {% endif %}
      </div>
      <div class="popup" id="popup">
        <span class="helper"></span>
        <div class="res" id="res">
          
        </div>
      </div>
  </body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript">
  $("#form_relawan").submit(function(e) {

    e.preventDefault();

    var form = $(this);
    var url = form.attr('action');

    $.ajax({
          type: "POST",
          url: url,
          data: form.serialize(),
          success: function(data){
            $(".popup").show();
            $('#res').empty();
            $('#res').append('<h2 align="center">Konfirmasi</h2>');
            $('#res').append('<p><b>Nama Relawan</b></p>');
            $('#res').append('<p>'+data.nama+'</p>');
            $('#res').append('<p><b>No handphone</b></p>');
            $('#res').append('<p>'+data.no_hp+'</p>');
            $('#res').append('<p><b>Email</b></p>');
            $('#res').append('<p>'+data.email+'</p>');
            $('#res').append('<p><b>No. Identitas</b></p>');
            $('#res').append('<p>'+data.no_identitas+'</p>');
            $('#res').append('<p><b>Jenis Kelamin</b></p>');
            $('#res').append('<p>'+data.jenis_kelamin+'</p>');
            $('#res').append('<p><b>Tanggal Lahir</b></p>');
            $('#res').append('<p>'+data.tanggal_lahir+'</p>');
            $('#res').append('<p><b>Agama</b></p>');
            $('#res').append('<p>'+data.agama+'</p>');
            $('#res').append('<p><b>Peminatan Cluster</b></p>');
            $('#res').append('<p>'+data.peminatan+'</p>');
            $('#res').append('<button type="button" class="btn btn-primary" style="display: block; margin: 0 auto;"><a style="text-decoration: none; color: white;" href="{% url "app4:confirm" %}">Confirm</a></button>');
            $('#res').append('<button id="back" onclick=$(".popup").hide()  class="btn btn-default" type="button" style="display: block; margin: 0 auto; margin-top: 10px;">Back</button>');
            
          }
    });
  })
</script>
{% endblock content %}
</html>

app4/templates/success.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}
<html>
  {% block content %} 
    <head>
      <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'cssfile/style.css' %}">
        <title>
            Pendaftaran Sukses
        </title>
    </head>
    
    <body style="background-color:orange; font-family: Rubik;">
      {% include 'base.html' %}
		  <div class="container">
        <div class="card" style="margin-top: 50px; margin-bottom: 50px;background-color: rgba(245, 245, 245, 0.9);">
          <div class="container">
            <div class="row">
              <img class="foto" src="{% static 'email.png' %}" style="margin-left:auto; margin-right: auto; margin-top: 20px; display: block; width: 200px; height: 200px;">  
            </div>
            <div class="row">
              <h3 style="margin-left:auto; margin-right: auto; margin-top: 20px;">Terima kasih telah melakukan registrasi!</h3>
            </div>
            <div class="row">
              <p style="text-align: center;margin-left:auto; margin-right: auto; margin-top: 20px;">Kami sangat mengapresiasi kebaikan anda untuk menjadi relawan kami. Kami telah mengirimkan email verifikasi untuk anda. Silahkan melakukan verifikasi data anda untuk menuju tahap selanjutnya. :)</p>
            </div>
            <div class="row">
                <div class="centre-items" style="margin-top: 50px; text-align: center; margin-left: auto;margin-right: auto;margin-bottom: 50px;">
                    <a href="{% url 'app1:home' %}"><button class="btn btn-primary">Menu Utama</button></a>    
                        </div>
                    </form>
                  
                </div>
        </div>
      </div>
      </div>
      {% endblock content %}
	</body>
</html>